<?php
$title = '创建应用';
$this->headTitle($title);
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>

<div class="table-responsive">
	<table class="table table-hover">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('dashboard/default', array('controller' => 'product', 'action' => 'create')));
$form->prepare();
echo $this->form()->openTag($form);
?>
		<tbody>
			<tr>
				<td>应用名称<?php echo $this->formHidden($form->get('id'));?></td>
				<td><?php echo $this->formrow($form->get('name'));?></td>
			</tr>
			<tr>
				<td>说明／备注</td>
				<td><?php echo $this->formrow($form->get('desc'));?></td>
			</tr>
			<tr>
				<td></td>
				<td><?php echo $this->formrow($form->get('submit'));?></td>
			</tr>
		</tbody>
<?php
echo $this->form()->closeTag();
?>
	</table>

</div>
