<div class="panel-body">
<h3>应用列表</h3>
<hr>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>ID</th>
					<th>AppName</th>
					<th>说明</th>
					<th>创建人</th>
					<th>创建时间</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($app as $a) : ?>
				<tr>
					<td><?php echo $a['_id']->__toString(); ?></td>
					<td><?php echo $a['name']; ?></td>
					<td><?php echo $a['desc']; ?></td>
					<td><?php echo $a['operator']; ?></td>
					<td><?php echo date('Y-m-d H:i:s', $a['timestamp']); ?></td>
					<td><a href="<?php echo $this->url('dashboard/default', array('controller' => 'product', 'action' => 'edit')) . $a['_id']->__toString(); ?>">编辑</a>&nbsp;|&nbsp;<a href="<?php echo $this->url('dashboard/default', array('controller' => 'product', 'action' => 'delete')) . $a['_id']->__toString(); ?>">删除</a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<!-- /.table-responsive -->

</div>
