<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <meta name="description" content="">
    <meta name="author" content="">
    <?php echo $this->headTitle('Config Master Dashboard')->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Bootstrap Core CSS -->
    <link href="/theme/sb2/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/theme/sb2/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/theme/sb2/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/theme/sb2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <!-- <link href="/theme/sb2/bower_components/morrisjs/morris.css" rel="stylesheet">  -->

    <!-- Custom Fonts -->
    <link href="/theme/sb2/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    <!-- jQuery UI -->
    <link href="/jqui112/jquery-ui.theme.min.css" rel="stylesheet" type="text/css">
    
    <!-- jQuery UI -->
    <link href="/jqui112/jquery-ui.structure.min.css" rel="stylesheet" type="text/css">
    
    <!-- jQuery UI -->
    <link href="/jqui112/jquery-ui.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <!-- jQuery -->
    <script src="/theme/sb2/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/theme/sb2/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/theme/sb2/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <!-- <script src="/theme/sb2/bower_components/raphael/raphael-min.js"></script> -->
    <!-- <script src="/theme/sb2/bower_components/morrisjs/morris.min.js"></script> -->
    <!-- <script src="/theme/sb2/js/morris-data.js"></script>  -->

    <!-- Custom Theme JavaScript -->
    <script src="/theme/sb2/dist/js/sb-admin-2.js"></script>
    
    <script src="/jqui112/jquery-ui.min.js"></script>

</head>

<body>

    <div id="wrapper">
        <?php echo $this->partial('sidebar');?>
        
        <div id="page-wrapper">
            <?php echo $this->content; ?>
            <hr>
            <!-- /.row -->
            <footer>
                <center><p>&copy; 2016 - <?php echo date('Y') ?> by Config Master Ltd. <?php echo $this->translate('All rights reserved.') ?></p></center>
            </footer>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->

</body>

</html>
