<?php
$title = '删除配置';
$this->headTitle($title);
?>
<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>

<hr>
<p>
	确认要删除  '<?php echo 'appid: '. $this->escapeHtml($config['appid']); ?> 的配置项 <?php echo $this->escapeHtml($config['key']); ?>'
</p>

<form
	action="<?php echo $this->url('dashboard/default',array('controller' => 'config', 'action' => 'delete', 'id' => $this->id)); ?>"
	method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $config['_id']->__toString(); ?>" /> 
		<input class="btn btn-danger" type="submit" name="del" value="Yes" /> 
		<input class="btn btn-outline btn-primary btn-lg" type="submit" name="del" value="No" />
	</div>
</form>