<?php
$title = '更新配置';
$this->headTitle($title);
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>

<div class="table-responsive">
	<table class="table table-hover">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('dashboard/default',array('controller' => 'config', 'action' => 'edit', 'id' => $this->id)));
$form->prepare();
echo $this->form()->openTag($form);
?>
		<tbody>
			<tr>
				<td>App<?php echo $this->formHidden($form->get('id'));?><?php echo $this->formHidden($form->get('version'));?></td>
				<td><?php echo $this->formrow($form->get('appid'));?></td>
			</tr>
			<tr>
				<td>文件位置</td>
				<td><?php echo $this->formrow($form->get('path'));?></td>
			</tr>
			<tr>
				<td>Key</td>
				<td><?php echo $this->formrow($form->get('key'));?></td>
			</tr>
			<tr>
				<td>Value</td>
				<td><?php echo $this->formrow($form->get('value'));?></td>
			</tr>
			<tr>
				<td>备注</td>
				<td><?php echo $this->formrow($form->get('desc'));?></td>
			</tr>
			<tr>
				<td></td>
				<td><?php echo $this->formrow($form->get('submit'));?></td>
			</tr>
		</tbody>
<?php
echo $this->form()->closeTag();
?>
	</table>

</div>
